import Link from "next/link";
import Head from "next/head";
import React from "react";
import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import Form from "react-bootstrap/Form";
import Nav from "react-bootstrap/Nav";
import Navbar from "react-bootstrap/Navbar";
import NavDropdown from "react-bootstrap/NavDropdown";
import Router from "next/router";
import Image from "next/image";
//import styles from "./styles.css";
import Offcanvas from "react-bootstrap/Offcanvas";
import { Black_And_White_Picture } from "next/font/google";
import { useRouter } from "next/router";

export default function Header(props) {
  const router = useRouter();
  const sentToLogin = () => {
    props.logout();
  };
  return (
    <div style={{ backgroundColor: "black" }}>
      {/* <Head>
        <title>Lions Pride Rx</title>
        <meta name="description" content="Generated by CureDoktor" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head> */}
      <div className="offer">
        <p>Get your first month + online doctor visit for only $10</p>
      </div>
      <Container>
        <Navbar collapseOnSelect={true} key={false} expand={false}>
          <Container fluid>
            <Navbar.Brand href="/">
              <Image
                src="/img/logo.svg"
                width={224}
                height={38}
                alt="LionsPrideRX"
                onClick={() => {
                  Router.push("/");
                }}
              />
            </Navbar.Brand>
            <Navbar.Toggle aria-controls={`offcanvasNavbar-expand-${false}`} />
            <Navbar.Offcanvas
              id={`offcanvasNavbar-expand-${false}`}
              aria-labelledby={`offcanvasNavbarLabel-expand-${false}`}
              placement="end"
            >
              <Offcanvas.Header closeButton></Offcanvas.Header>
              <Offcanvas.Body className="offcanvas-body">
                <Nav.Link href="/">Home</Nav.Link>
                <Nav.Link href="/how-it-works">How it Works</Nav.Link>
                <Nav.Link href="/#faq">FAQs</Nav.Link>

                {/* <li>
                    <Link href="/">Home</Link>
                  </li>
                  <li>
                    <Link href="/how-it-works">How it Works</Link>
                  </li>
                  <li>
                    <Link href="/#faq">FAQs</Link>
                  </li> */}
                {/* <Nav.Link href="/about">About Us</Nav.Link>
                <Nav.Link href="/contact">Contact</Nav.Link>
                <Nav.Link href="/faq">FAQs</Nav.Link>
                <Nav.Link href="/blog">Blog</Nav.Link> */}

                {props.header ? (
                  <Link href="/profile" passHref>
                    Account
                  </Link>
                ) : (
                  ""
                )}
                {props.header ? (
                  <Button className="d-block mt-3" onClick={sentToLogin}>
                    {props.header ? "LOGOUT" : "LOGIN"}
                  </Button>
                ) : (
                  <Button
                    className="d-block mt-3"
                    onClick={() => {
                      router.push("/login");
                    }}
                  >
                    LOGIN
                  </Button>
                )}
              </Offcanvas.Body>
            </Navbar.Offcanvas>
          </Container>
        </Navbar>
      </Container>
    </div>
  );
}
