import Head from "next/head";
import { useContext, useState, React } from "react";
import { Col, Container, Button, Row } from "react-bootstrap";
import Nav from "react-bootstrap/Nav";
import Orders from "../../../components/Orders";
import Membership from "../../../components/Membership";
import Profile from "../../../components/Profile";
import Case from "../../../components/Case";
import styles from "./styles.module.scss";
import { black } from "picocolors";
import { bottom } from "@popperjs/core";
export default function Account() {
  const [checked, setChecked] = useState(false);
  const [content, setContent] = useState(<Membership />);
  const [key, setKey] = useState("Membership");

  const handleSelect = (link) => {
    console.log("Cure");
    if (link === "Membership") {
      setContent(<Membership />);
    } else if (link === "Orders") {
      setContent(<Orders />);
    } else if (link === "Profile") {
      setContent(<Profile />);
    } else if (link === "Case") {
      setContent(<Case />);
    }
  };

  const ActiveStyle = {
    color: "red",
    borderBottom: "3px solid red",
    padding: "5px",
    margin: "5px",
    background: "none",
  };

  const InactiveStyle = {
    background: "white",
    padding: "5px",
    margin: "5px",
    background: "none",
  };

  return (
    <div>
      <Head>
        <title>Lions Pride Rx - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container className={styles.cure}>
          <Nav
            onSelect={handleSelect}
            onClick={(key) => setKey(key)}
            variant="tabs"
            activeKey={key}
            defaultActiveKey="/home"
          >
            <Nav.Item>
              <Nav.Link eventKey="Membership">Membership</Nav.Link>
            </Nav.Item>
            <Nav.Item>
              <Nav.Link
                style={key == "Orders" ? ActiveStyle : InactiveStyle}
                eventKey="Orders"
              >
                Orders
              </Nav.Link>
            </Nav.Item>
            <Nav.Item>
              <Nav.Link
                style={key == "Profile" ? ActiveStyle : InactiveStyle}
                eventKey="Profile"
              >
                Profile
              </Nav.Link>
            </Nav.Item>
            <Nav.Item>
              <Nav.Link
                style={key == "Case" ? ActiveStyle : InactiveStyle}
                eventKey="Case"
              >
                Case
              </Nav.Link>
            </Nav.Item>
            <Nav.Item>
              <Nav.Link
                style={key == "ID Verification" ? ActiveStyle : InactiveStyle}
                eventKey="ID Verification"
              >
                ID Verification
              </Nav.Link>
            </Nav.Item>
          </Nav>
          <br />
          <br />
          {content}
        </Container>
      </main>
    </div>
  );
}
